// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/hassmic.proto

package com.thejeffcooper.hassmic.proto;

public interface AudioDataOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:hassmic.AudioData)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   *
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
