// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hassmic.proto

package com.thejeffcooper.hassmic.proto;

public interface ClientMessageOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:hassmic.ClientMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.hassmic.Ping ping = 1;</code>
   *
   * @return Whether the ping field is set.
   */
  boolean hasPing();

  /**
   * <code>.hassmic.Ping ping = 1;</code>
   *
   * @return The ping.
   */
  com.thejeffcooper.hassmic.proto.Ping getPing();

  /**
   * <code>.hassmic.ClientInfo client_info = 2;</code>
   *
   * @return Whether the clientInfo field is set.
   */
  boolean hasClientInfo();

  /**
   * <code>.hassmic.ClientInfo client_info = 2;</code>
   *
   * @return The clientInfo.
   */
  com.thejeffcooper.hassmic.proto.ClientInfo getClientInfo();

  /**
   * <code>.hassmic.AudioData audio_data = 3;</code>
   *
   * @return Whether the audioData field is set.
   */
  boolean hasAudioData();

  /**
   * <code>.hassmic.AudioData audio_data = 3;</code>
   *
   * @return The audioData.
   */
  com.thejeffcooper.hassmic.proto.AudioData getAudioData();

  /**
   * <code>.hassmic.ClientEvent event_occurred = 4;</code>
   *
   * @return Whether the eventOccurred field is set.
   */
  boolean hasEventOccurred();

  /**
   * <code>.hassmic.ClientEvent event_occurred = 4;</code>
   *
   * @return The enum numeric value on the wire for eventOccurred.
   */
  int getEventOccurredValue();

  /**
   * <code>.hassmic.ClientEvent event_occurred = 4;</code>
   *
   * @return The eventOccurred.
   */
  com.thejeffcooper.hassmic.proto.ClientEvent getEventOccurred();

  public com.thejeffcooper.hassmic.proto.ClientMessage.MsgCase getMsgCase();
}
