// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/hassmic.proto

package com.thejeffcooper.hassmic.proto;

public interface ClientMessageOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:hassmic.ClientMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.hassmic.Ping ping = 1;</code>
   *
   * @return Whether the ping field is set.
   */
  boolean hasPing();

  /**
   * <code>.hassmic.Ping ping = 1;</code>
   *
   * @return The ping.
   */
  com.thejeffcooper.hassmic.proto.Ping getPing();

  /**
   * <code>.hassmic.ClientInfo client_info = 2;</code>
   *
   * @return Whether the clientInfo field is set.
   */
  boolean hasClientInfo();

  /**
   * <code>.hassmic.ClientInfo client_info = 2;</code>
   *
   * @return The clientInfo.
   */
  com.thejeffcooper.hassmic.proto.ClientInfo getClientInfo();

  public com.thejeffcooper.hassmic.proto.ClientMessage.MsgCase getMsgCase();
}
