// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hassmic.proto

package com.thejeffcooper.hassmic.proto;

public interface ClientMessageOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:hassmic.ClientMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.hassmic.Ping ping = 1;</code>
   *
   * @return Whether the ping field is set.
   */
  boolean hasPing();

  /**
   * <code>.hassmic.Ping ping = 1;</code>
   *
   * @return The ping.
   */
  com.thejeffcooper.hassmic.proto.Ping getPing();

  /**
   * <code>.hassmic.ClientInfo client_info = 2;</code>
   *
   * @return Whether the clientInfo field is set.
   */
  boolean hasClientInfo();

  /**
   * <code>.hassmic.ClientInfo client_info = 2;</code>
   *
   * @return The clientInfo.
   */
  com.thejeffcooper.hassmic.proto.ClientInfo getClientInfo();

  /**
   * <code>.hassmic.AudioData audio_data = 3;</code>
   *
   * @return Whether the audioData field is set.
   */
  boolean hasAudioData();

  /**
   * <code>.hassmic.AudioData audio_data = 3;</code>
   *
   * @return The audioData.
   */
  com.thejeffcooper.hassmic.proto.AudioData getAudioData();

  /**
   * <code>.hassmic.ClientEvent client_event = 4;</code>
   *
   * @return Whether the clientEvent field is set.
   */
  boolean hasClientEvent();

  /**
   * <code>.hassmic.ClientEvent client_event = 4;</code>
   *
   * @return The clientEvent.
   */
  com.thejeffcooper.hassmic.proto.ClientEvent getClientEvent();

  public com.thejeffcooper.hassmic.proto.ClientMessage.MsgCase getMsgCase();
}
