// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hassmic.proto

package com.thejeffcooper.hassmic.proto;

public interface ClientEventOccurredOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:hassmic.ClientEventOccurred)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.hassmic.ClientEvent event = 1;</code>
   *
   * @return The enum numeric value on the wire for event.
   */
  int getEventValue();

  /**
   * <code>.hassmic.ClientEvent event = 1;</code>
   *
   * @return The event.
   */
  com.thejeffcooper.hassmic.proto.ClientEvent getEvent();
}
