// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hassmic.proto

package com.thejeffcooper.hassmic.proto;

/**
 *
 *
 * <pre>
 * Events that the client wants to make the server aware of
 * </pre>
 *
 * Protobuf enum {@code hassmic.ClientEvent}
 */
public enum ClientEvent implements com.google.protobuf.Internal.EnumLite {
  /** <code>UNKNOWN_EVENT = 0;</code> */
  UNKNOWN_EVENT(0),
  UNRECOGNIZED(-1),
  ;

  /** <code>UNKNOWN_EVENT = 0;</code> */
  public static final int UNKNOWN_EVENT_VALUE = 0;

  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ClientEvent valueOf(int value) {
    return forNumber(value);
  }

  public static ClientEvent forNumber(int value) {
    switch (value) {
      case 0:
        return UNKNOWN_EVENT;
      default:
        return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ClientEvent> internalGetValueMap() {
    return internalValueMap;
  }

  private static final com.google.protobuf.Internal.EnumLiteMap<ClientEvent> internalValueMap =
      new com.google.protobuf.Internal.EnumLiteMap<ClientEvent>() {
        @java.lang.Override
        public ClientEvent findValueByNumber(int number) {
          return ClientEvent.forNumber(number);
        }
      };

  public static com.google.protobuf.Internal.EnumVerifier internalGetVerifier() {
    return ClientEventVerifier.INSTANCE;
  }

  private static final class ClientEventVerifier
      implements com.google.protobuf.Internal.EnumVerifier {
    static final com.google.protobuf.Internal.EnumVerifier INSTANCE = new ClientEventVerifier();

    @java.lang.Override
    public boolean isInRange(int number) {
      return ClientEvent.forNumber(number) != null;
    }
  }
  ;

  private final int value;

  private ClientEvent(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:hassmic.ClientEvent)
}
