// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hassmic.proto

package com.thejeffcooper.hassmic.proto;

public interface DeviceVolumeChangeOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:hassmic.DeviceVolumeChange)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>float new_volume = 1;</code>
   *
   * @return The newVolume.
   */
  float getNewVolume();
}
