// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hassmic.proto

package com.thejeffcooper.hassmic.proto;

/**
 *
 *
 * <pre>
 * The device volume has changed
 * </pre>
 *
 * Protobuf type {@code hassmic.DeviceVolumeChange}
 */
public final class DeviceVolumeChange
    extends com.google.protobuf.GeneratedMessageLite<DeviceVolumeChange, DeviceVolumeChange.Builder>
    implements
    // @@protoc_insertion_point(message_implements:hassmic.DeviceVolumeChange)
    DeviceVolumeChangeOrBuilder {
  private DeviceVolumeChange() {}

  public static final int NEW_VOLUME_FIELD_NUMBER = 1;
  private float newVolume_;

  /**
   * <code>float new_volume = 1;</code>
   *
   * @return The newVolume.
   */
  @java.lang.Override
  public float getNewVolume() {
    return newVolume_;
  }

  /**
   * <code>float new_volume = 1;</code>
   *
   * @param value The newVolume to set.
   */
  private void setNewVolume(float value) {

    newVolume_ = value;
  }

  /** <code>float new_volume = 1;</code> */
  private void clearNewVolume() {

    newVolume_ = 0F;
  }

  public static com.thejeffcooper.hassmic.proto.DeviceVolumeChange parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.thejeffcooper.hassmic.proto.DeviceVolumeChange parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.DeviceVolumeChange parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.thejeffcooper.hassmic.proto.DeviceVolumeChange parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.DeviceVolumeChange parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.thejeffcooper.hassmic.proto.DeviceVolumeChange parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.DeviceVolumeChange parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static com.thejeffcooper.hassmic.proto.DeviceVolumeChange parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.DeviceVolumeChange parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.thejeffcooper.hassmic.proto.DeviceVolumeChange parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.DeviceVolumeChange parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static com.thejeffcooper.hassmic.proto.DeviceVolumeChange parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }

  public static Builder newBuilder(com.thejeffcooper.hassmic.proto.DeviceVolumeChange prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   *
   *
   * <pre>
   * The device volume has changed
   * </pre>
   *
   * Protobuf type {@code hassmic.DeviceVolumeChange}
   */
  public static final class Builder
      extends com.google.protobuf.GeneratedMessageLite.Builder<
          com.thejeffcooper.hassmic.proto.DeviceVolumeChange, Builder>
      implements
      // @@protoc_insertion_point(builder_implements:hassmic.DeviceVolumeChange)
      com.thejeffcooper.hassmic.proto.DeviceVolumeChangeOrBuilder {
    // Construct using com.thejeffcooper.hassmic.proto.DeviceVolumeChange.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    /**
     * <code>float new_volume = 1;</code>
     *
     * @return The newVolume.
     */
    @java.lang.Override
    public float getNewVolume() {
      return instance.getNewVolume();
    }

    /**
     * <code>float new_volume = 1;</code>
     *
     * @param value The newVolume to set.
     * @return This builder for chaining.
     */
    public Builder setNewVolume(float value) {
      copyOnWrite();
      instance.setNewVolume(value);
      return this;
    }

    /**
     * <code>float new_volume = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearNewVolume() {
      copyOnWrite();
      instance.clearNewVolume();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:hassmic.DeviceVolumeChange)
  }

  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0,
      java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE:
        {
          return new com.thejeffcooper.hassmic.proto.DeviceVolumeChange();
        }
      case NEW_BUILDER:
        {
          return new Builder();
        }
      case BUILD_MESSAGE_INFO:
        {
          java.lang.Object[] objects =
              new java.lang.Object[] {
                "newVolume_",
              };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0001";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
      case GET_DEFAULT_INSTANCE:
        {
          return DEFAULT_INSTANCE;
        }
      case GET_PARSER:
        {
          com.google.protobuf.Parser<com.thejeffcooper.hassmic.proto.DeviceVolumeChange> parser =
              PARSER;
          if (parser == null) {
            synchronized (com.thejeffcooper.hassmic.proto.DeviceVolumeChange.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<
                        com.thejeffcooper.hassmic.proto.DeviceVolumeChange>(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
      case GET_MEMOIZED_IS_INITIALIZED:
        {
          return (byte) 1;
        }
      case SET_MEMOIZED_IS_INITIALIZED:
        {
          return null;
        }
    }
    throw new UnsupportedOperationException();
  }

  // @@protoc_insertion_point(class_scope:hassmic.DeviceVolumeChange)
  private static final com.thejeffcooper.hassmic.proto.DeviceVolumeChange DEFAULT_INSTANCE;

  static {
    DeviceVolumeChange defaultInstance = new DeviceVolumeChange();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        DeviceVolumeChange.class, defaultInstance);
  }

  public static com.thejeffcooper.hassmic.proto.DeviceVolumeChange getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DeviceVolumeChange> PARSER;

  public static com.google.protobuf.Parser<DeviceVolumeChange> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
