// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hassmic.proto

package com.thejeffcooper.hassmic.proto;

/**
 *
 *
 * <pre>
 * A log message passed from the client to the server
 * </pre>
 *
 * Protobuf type {@code hassmic.Log}
 */
public final class Log extends com.google.protobuf.GeneratedMessageLite<Log, Log.Builder>
    implements
    // @@protoc_insertion_point(message_implements:hassmic.Log)
    LogOrBuilder {
  private Log() {
    logText_ = "";
  }

  public static final int LOG_TEXT_FIELD_NUMBER = 1;
  private java.lang.String logText_;

  /**
   * <code>string log_text = 1;</code>
   *
   * @return The logText.
   */
  @java.lang.Override
  public java.lang.String getLogText() {
    return logText_;
  }

  /**
   * <code>string log_text = 1;</code>
   *
   * @return The bytes for logText.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getLogTextBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(logText_);
  }

  /**
   * <code>string log_text = 1;</code>
   *
   * @param value The logText to set.
   */
  private void setLogText(java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();

    logText_ = value;
  }

  /** <code>string log_text = 1;</code> */
  private void clearLogText() {

    logText_ = getDefaultInstance().getLogText();
  }

  /**
   * <code>string log_text = 1;</code>
   *
   * @param value The bytes for logText to set.
   */
  private void setLogTextBytes(com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    logText_ = value.toStringUtf8();
  }

  public static com.thejeffcooper.hassmic.proto.Log parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.thejeffcooper.hassmic.proto.Log parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.Log parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.thejeffcooper.hassmic.proto.Log parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.Log parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.thejeffcooper.hassmic.proto.Log parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.Log parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static com.thejeffcooper.hassmic.proto.Log parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.Log parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.thejeffcooper.hassmic.proto.Log parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.Log parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static com.thejeffcooper.hassmic.proto.Log parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }

  public static Builder newBuilder(com.thejeffcooper.hassmic.proto.Log prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   *
   *
   * <pre>
   * A log message passed from the client to the server
   * </pre>
   *
   * Protobuf type {@code hassmic.Log}
   */
  public static final class Builder
      extends com.google.protobuf.GeneratedMessageLite.Builder<
          com.thejeffcooper.hassmic.proto.Log, Builder>
      implements
      // @@protoc_insertion_point(builder_implements:hassmic.Log)
      com.thejeffcooper.hassmic.proto.LogOrBuilder {
    // Construct using com.thejeffcooper.hassmic.proto.Log.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    /**
     * <code>string log_text = 1;</code>
     *
     * @return The logText.
     */
    @java.lang.Override
    public java.lang.String getLogText() {
      return instance.getLogText();
    }

    /**
     * <code>string log_text = 1;</code>
     *
     * @return The bytes for logText.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLogTextBytes() {
      return instance.getLogTextBytes();
    }

    /**
     * <code>string log_text = 1;</code>
     *
     * @param value The logText to set.
     * @return This builder for chaining.
     */
    public Builder setLogText(java.lang.String value) {
      copyOnWrite();
      instance.setLogText(value);
      return this;
    }

    /**
     * <code>string log_text = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearLogText() {
      copyOnWrite();
      instance.clearLogText();
      return this;
    }

    /**
     * <code>string log_text = 1;</code>
     *
     * @param value The bytes for logText to set.
     * @return This builder for chaining.
     */
    public Builder setLogTextBytes(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLogTextBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:hassmic.Log)
  }

  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0,
      java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE:
        {
          return new com.thejeffcooper.hassmic.proto.Log();
        }
      case NEW_BUILDER:
        {
          return new Builder();
        }
      case BUILD_MESSAGE_INFO:
        {
          java.lang.Object[] objects =
              new java.lang.Object[] {
                "logText_",
              };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
      case GET_DEFAULT_INSTANCE:
        {
          return DEFAULT_INSTANCE;
        }
      case GET_PARSER:
        {
          com.google.protobuf.Parser<com.thejeffcooper.hassmic.proto.Log> parser = PARSER;
          if (parser == null) {
            synchronized (com.thejeffcooper.hassmic.proto.Log.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.thejeffcooper.hassmic.proto.Log>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
      case GET_MEMOIZED_IS_INITIALIZED:
        {
          return (byte) 1;
        }
      case SET_MEMOIZED_IS_INITIALIZED:
        {
          return null;
        }
    }
    throw new UnsupportedOperationException();
  }

  // @@protoc_insertion_point(class_scope:hassmic.Log)
  private static final com.thejeffcooper.hassmic.proto.Log DEFAULT_INSTANCE;

  static {
    Log defaultInstance = new Log();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(Log.class, defaultInstance);
  }

  public static com.thejeffcooper.hassmic.proto.Log getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Log> PARSER;

  public static com.google.protobuf.Parser<Log> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
