// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hassmic.proto

package com.thejeffcooper.hassmic.proto;

public interface LogOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:hassmic.Log)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string log_text = 1;</code>
   *
   * @return The logText.
   */
  java.lang.String getLogText();

  /**
   * <code>string log_text = 1;</code>
   *
   * @return The bytes for logText.
   */
  com.google.protobuf.ByteString getLogTextBytes();
}
