// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hassmic.proto

package com.thejeffcooper.hassmic.proto;

/** Protobuf enum {@code hassmic.MediaPlayerCommand} */
public enum MediaPlayerCommand implements com.google.protobuf.Internal.EnumLite {
  /** <code>COMMAND_UNKNOWN = 0;</code> */
  COMMAND_UNKNOWN(0),
  /** <code>COMMAND_PLAY = 1;</code> */
  COMMAND_PLAY(1),
  /** <code>COMMAND_PAUSE = 2;</code> */
  COMMAND_PAUSE(2),
  UNRECOGNIZED(-1),
  ;

  /** <code>COMMAND_UNKNOWN = 0;</code> */
  public static final int COMMAND_UNKNOWN_VALUE = 0;

  /** <code>COMMAND_PLAY = 1;</code> */
  public static final int COMMAND_PLAY_VALUE = 1;

  /** <code>COMMAND_PAUSE = 2;</code> */
  public static final int COMMAND_PAUSE_VALUE = 2;

  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MediaPlayerCommand valueOf(int value) {
    return forNumber(value);
  }

  public static MediaPlayerCommand forNumber(int value) {
    switch (value) {
      case 0:
        return COMMAND_UNKNOWN;
      case 1:
        return COMMAND_PLAY;
      case 2:
        return COMMAND_PAUSE;
      default:
        return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MediaPlayerCommand> internalGetValueMap() {
    return internalValueMap;
  }

  private static final com.google.protobuf.Internal.EnumLiteMap<MediaPlayerCommand>
      internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MediaPlayerCommand>() {
            @java.lang.Override
            public MediaPlayerCommand findValueByNumber(int number) {
              return MediaPlayerCommand.forNumber(number);
            }
          };

  public static com.google.protobuf.Internal.EnumVerifier internalGetVerifier() {
    return MediaPlayerCommandVerifier.INSTANCE;
  }

  private static final class MediaPlayerCommandVerifier
      implements com.google.protobuf.Internal.EnumVerifier {
    static final com.google.protobuf.Internal.EnumVerifier INSTANCE =
        new MediaPlayerCommandVerifier();

    @java.lang.Override
    public boolean isInRange(int number) {
      return MediaPlayerCommand.forNumber(number) != null;
    }
  }
  ;

  private final int value;

  private MediaPlayerCommand(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:hassmic.MediaPlayerCommand)
}
