// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hassmic.proto

package com.thejeffcooper.hassmic.proto;

/**
 *
 *
 * <pre>
 * A media player has changed volume
 * </pre>
 *
 * Protobuf type {@code hassmic.MediaPlayerVolumeChange}
 */
public final class MediaPlayerVolumeChange
    extends com.google.protobuf.GeneratedMessageLite<
        MediaPlayerVolumeChange, MediaPlayerVolumeChange.Builder>
    implements
    // @@protoc_insertion_point(message_implements:hassmic.MediaPlayerVolumeChange)
    MediaPlayerVolumeChangeOrBuilder {
  private MediaPlayerVolumeChange() {}

  public static final int PLAYER_FIELD_NUMBER = 1;
  private int player_;

  /**
   * <code>.hassmic.MediaPlayerId player = 1;</code>
   *
   * @return The enum numeric value on the wire for player.
   */
  @java.lang.Override
  public int getPlayerValue() {
    return player_;
  }

  /**
   * <code>.hassmic.MediaPlayerId player = 1;</code>
   *
   * @return The player.
   */
  @java.lang.Override
  public com.thejeffcooper.hassmic.proto.MediaPlayerId getPlayer() {
    com.thejeffcooper.hassmic.proto.MediaPlayerId result =
        com.thejeffcooper.hassmic.proto.MediaPlayerId.forNumber(player_);
    return result == null ? com.thejeffcooper.hassmic.proto.MediaPlayerId.UNRECOGNIZED : result;
  }

  /**
   * <code>.hassmic.MediaPlayerId player = 1;</code>
   *
   * @param value The enum numeric value on the wire for player to set.
   */
  private void setPlayerValue(int value) {
    player_ = value;
  }

  /**
   * <code>.hassmic.MediaPlayerId player = 1;</code>
   *
   * @param value The player to set.
   */
  private void setPlayer(com.thejeffcooper.hassmic.proto.MediaPlayerId value) {
    player_ = value.getNumber();
  }

  /** <code>.hassmic.MediaPlayerId player = 1;</code> */
  private void clearPlayer() {

    player_ = 0;
  }

  public static final int NEW_VOLUME_FIELD_NUMBER = 2;
  private float newVolume_;

  /**
   * <code>float new_volume = 2;</code>
   *
   * @return The newVolume.
   */
  @java.lang.Override
  public float getNewVolume() {
    return newVolume_;
  }

  /**
   * <code>float new_volume = 2;</code>
   *
   * @param value The newVolume to set.
   */
  private void setNewVolume(float value) {

    newVolume_ = value;
  }

  /** <code>float new_volume = 2;</code> */
  private void clearNewVolume() {

    newVolume_ = 0F;
  }

  public static com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }

  public static Builder newBuilder(
      com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   *
   *
   * <pre>
   * A media player has changed volume
   * </pre>
   *
   * Protobuf type {@code hassmic.MediaPlayerVolumeChange}
   */
  public static final class Builder
      extends com.google.protobuf.GeneratedMessageLite.Builder<
          com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange, Builder>
      implements
      // @@protoc_insertion_point(builder_implements:hassmic.MediaPlayerVolumeChange)
      com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChangeOrBuilder {
    // Construct using com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    /**
     * <code>.hassmic.MediaPlayerId player = 1;</code>
     *
     * @return The enum numeric value on the wire for player.
     */
    @java.lang.Override
    public int getPlayerValue() {
      return instance.getPlayerValue();
    }

    /**
     * <code>.hassmic.MediaPlayerId player = 1;</code>
     *
     * @param value The player to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerValue(int value) {
      copyOnWrite();
      instance.setPlayerValue(value);
      return this;
    }

    /**
     * <code>.hassmic.MediaPlayerId player = 1;</code>
     *
     * @return The player.
     */
    @java.lang.Override
    public com.thejeffcooper.hassmic.proto.MediaPlayerId getPlayer() {
      return instance.getPlayer();
    }

    /**
     * <code>.hassmic.MediaPlayerId player = 1;</code>
     *
     * @param value The enum numeric value on the wire for player to set.
     * @return This builder for chaining.
     */
    public Builder setPlayer(com.thejeffcooper.hassmic.proto.MediaPlayerId value) {
      copyOnWrite();
      instance.setPlayer(value);
      return this;
    }

    /**
     * <code>.hassmic.MediaPlayerId player = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearPlayer() {
      copyOnWrite();
      instance.clearPlayer();
      return this;
    }

    /**
     * <code>float new_volume = 2;</code>
     *
     * @return The newVolume.
     */
    @java.lang.Override
    public float getNewVolume() {
      return instance.getNewVolume();
    }

    /**
     * <code>float new_volume = 2;</code>
     *
     * @param value The newVolume to set.
     * @return This builder for chaining.
     */
    public Builder setNewVolume(float value) {
      copyOnWrite();
      instance.setNewVolume(value);
      return this;
    }

    /**
     * <code>float new_volume = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearNewVolume() {
      copyOnWrite();
      instance.clearNewVolume();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:hassmic.MediaPlayerVolumeChange)
  }

  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0,
      java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE:
        {
          return new com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange();
        }
      case NEW_BUILDER:
        {
          return new Builder();
        }
      case BUILD_MESSAGE_INFO:
        {
          java.lang.Object[] objects =
              new java.lang.Object[] {
                "player_", "newVolume_",
              };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\f\u0002\u0001"
                  + "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
      case GET_DEFAULT_INSTANCE:
        {
          return DEFAULT_INSTANCE;
        }
      case GET_PARSER:
        {
          com.google.protobuf.Parser<com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange>
              parser = PARSER;
          if (parser == null) {
            synchronized (com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<
                        com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange>(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
      case GET_MEMOIZED_IS_INITIALIZED:
        {
          return (byte) 1;
        }
      case SET_MEMOIZED_IS_INITIALIZED:
        {
          return null;
        }
    }
    throw new UnsupportedOperationException();
  }

  // @@protoc_insertion_point(class_scope:hassmic.MediaPlayerVolumeChange)
  private static final com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange DEFAULT_INSTANCE;

  static {
    MediaPlayerVolumeChange defaultInstance = new MediaPlayerVolumeChange();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        MediaPlayerVolumeChange.class, defaultInstance);
  }

  public static com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<MediaPlayerVolumeChange> PARSER;

  public static com.google.protobuf.Parser<MediaPlayerVolumeChange> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
