// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hassmic.proto

package com.thejeffcooper.hassmic.proto;

/**
 *
 *
 * <pre>
 * https://developer.android.com/reference/androidx/media3/common/Player.State
 * </pre>
 *
 * Protobuf enum {@code hassmic.MediaPlayerState}
 */
public enum MediaPlayerState implements com.google.protobuf.Internal.EnumLite {
  /** <code>STATE_UNKNOWN = 0;</code> */
  STATE_UNKNOWN(0),
  /** <code>STATE_IDLE = 1;</code> */
  STATE_IDLE(1),
  /** <code>STATE_BUFFERING = 2;</code> */
  STATE_BUFFERING(2),
  /** <code>STATE_READY = 3;</code> */
  STATE_READY(3),
  /** <code>STATE_ENDED = 4;</code> */
  STATE_ENDED(4),
  UNRECOGNIZED(-1),
  ;

  /** <code>STATE_UNKNOWN = 0;</code> */
  public static final int STATE_UNKNOWN_VALUE = 0;

  /** <code>STATE_IDLE = 1;</code> */
  public static final int STATE_IDLE_VALUE = 1;

  /** <code>STATE_BUFFERING = 2;</code> */
  public static final int STATE_BUFFERING_VALUE = 2;

  /** <code>STATE_READY = 3;</code> */
  public static final int STATE_READY_VALUE = 3;

  /** <code>STATE_ENDED = 4;</code> */
  public static final int STATE_ENDED_VALUE = 4;

  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MediaPlayerState valueOf(int value) {
    return forNumber(value);
  }

  public static MediaPlayerState forNumber(int value) {
    switch (value) {
      case 0:
        return STATE_UNKNOWN;
      case 1:
        return STATE_IDLE;
      case 2:
        return STATE_BUFFERING;
      case 3:
        return STATE_READY;
      case 4:
        return STATE_ENDED;
      default:
        return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MediaPlayerState> internalGetValueMap() {
    return internalValueMap;
  }

  private static final com.google.protobuf.Internal.EnumLiteMap<MediaPlayerState> internalValueMap =
      new com.google.protobuf.Internal.EnumLiteMap<MediaPlayerState>() {
        @java.lang.Override
        public MediaPlayerState findValueByNumber(int number) {
          return MediaPlayerState.forNumber(number);
        }
      };

  public static com.google.protobuf.Internal.EnumVerifier internalGetVerifier() {
    return MediaPlayerStateVerifier.INSTANCE;
  }

  private static final class MediaPlayerStateVerifier
      implements com.google.protobuf.Internal.EnumVerifier {
    static final com.google.protobuf.Internal.EnumVerifier INSTANCE =
        new MediaPlayerStateVerifier();

    @java.lang.Override
    public boolean isInRange(int number) {
      return MediaPlayerState.forNumber(number) != null;
    }
  }
  ;

  private final int value;

  private MediaPlayerState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:hassmic.MediaPlayerState)
}
