// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/hassmic.proto

package com.thejeffcooper.hassmic.proto;

public interface PingOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:hassmic.Ping)
    com.google.protobuf.MessageLiteOrBuilder {}
