// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hassmic.proto

package com.thejeffcooper.hassmic.proto;

public interface SavedSettingsOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:hassmic.SavedSettings)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   *
   *
   * <pre>
   * The last volume of the `announce` player
   * </pre>
   *
   * <code>float announce_volume = 1;</code>
   *
   * @return The announceVolume.
   */
  float getAnnounceVolume();

  /**
   *
   *
   * <pre>
   * The last volume of the `playback` player
   * </pre>
   *
   * <code>float playback_volume = 2;</code>
   *
   * @return The playbackVolume.
   */
  float getPlaybackVolume();
}
