// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hassmic.proto

package com.thejeffcooper.hassmic.proto;

/**
 *
 *
 * <pre>
 * The wrapper message that gets sent from the server to the client
 * </pre>
 *
 * Protobuf type {@code hassmic.ServerMessage}
 */
public final class ServerMessage
    extends com.google.protobuf.GeneratedMessageLite<ServerMessage, ServerMessage.Builder>
    implements
    // @@protoc_insertion_point(message_implements:hassmic.ServerMessage)
    ServerMessageOrBuilder {
  private ServerMessage() {}

  private int msgCase_ = 0;
  private java.lang.Object msg_;

  public enum MsgCase {
    PLAY_AUDIO(1),
    SET_MIC_MUTE(2),
    SET_DEVICE_VOLUME(3),
    SET_PLAYER_VOLUME(4),
    MSG_NOT_SET(0);
    private final int value;

    private MsgCase(int value) {
      this.value = value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgCase valueOf(int value) {
      return forNumber(value);
    }

    public static MsgCase forNumber(int value) {
      switch (value) {
        case 1:
          return PLAY_AUDIO;
        case 2:
          return SET_MIC_MUTE;
        case 3:
          return SET_DEVICE_VOLUME;
        case 4:
          return SET_PLAYER_VOLUME;
        case 0:
          return MSG_NOT_SET;
        default:
          return null;
      }
    }

    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public MsgCase getMsgCase() {
    return MsgCase.forNumber(msgCase_);
  }

  private void clearMsg() {
    msgCase_ = 0;
    msg_ = null;
  }

  public static final int PLAY_AUDIO_FIELD_NUMBER = 1;

  /**
   *
   *
   * <pre>
   * A command to play audio
   * </pre>
   *
   * <code>.hassmic.PlayAudio play_audio = 1;</code>
   */
  @java.lang.Override
  public boolean hasPlayAudio() {
    return msgCase_ == 1;
  }

  /**
   *
   *
   * <pre>
   * A command to play audio
   * </pre>
   *
   * <code>.hassmic.PlayAudio play_audio = 1;</code>
   */
  @java.lang.Override
  public com.thejeffcooper.hassmic.proto.PlayAudio getPlayAudio() {
    if (msgCase_ == 1) {
      return (com.thejeffcooper.hassmic.proto.PlayAudio) msg_;
    }
    return com.thejeffcooper.hassmic.proto.PlayAudio.getDefaultInstance();
  }

  /**
   *
   *
   * <pre>
   * A command to play audio
   * </pre>
   *
   * <code>.hassmic.PlayAudio play_audio = 1;</code>
   */
  private void setPlayAudio(com.thejeffcooper.hassmic.proto.PlayAudio value) {
    value.getClass();
    msg_ = value;
    msgCase_ = 1;
  }

  /**
   *
   *
   * <pre>
   * A command to play audio
   * </pre>
   *
   * <code>.hassmic.PlayAudio play_audio = 1;</code>
   */
  private void mergePlayAudio(com.thejeffcooper.hassmic.proto.PlayAudio value) {
    value.getClass();
    if (msgCase_ == 1 && msg_ != com.thejeffcooper.hassmic.proto.PlayAudio.getDefaultInstance()) {
      msg_ =
          com.thejeffcooper.hassmic.proto.PlayAudio.newBuilder(
                  (com.thejeffcooper.hassmic.proto.PlayAudio) msg_)
              .mergeFrom(value)
              .buildPartial();
    } else {
      msg_ = value;
    }
    msgCase_ = 1;
  }

  /**
   *
   *
   * <pre>
   * A command to play audio
   * </pre>
   *
   * <code>.hassmic.PlayAudio play_audio = 1;</code>
   */
  private void clearPlayAudio() {
    if (msgCase_ == 1) {
      msgCase_ = 0;
      msg_ = null;
    }
  }

  public static final int SET_MIC_MUTE_FIELD_NUMBER = 2;

  /**
   *
   *
   * <pre>
   * Set whether the mic should be muted
   * </pre>
   *
   * <code>bool set_mic_mute = 2;</code>
   *
   * @return Whether the setMicMute field is set.
   */
  @java.lang.Override
  public boolean hasSetMicMute() {
    return msgCase_ == 2;
  }

  /**
   *
   *
   * <pre>
   * Set whether the mic should be muted
   * </pre>
   *
   * <code>bool set_mic_mute = 2;</code>
   *
   * @return The setMicMute.
   */
  @java.lang.Override
  public boolean getSetMicMute() {
    if (msgCase_ == 2) {
      return (java.lang.Boolean) msg_;
    }
    return false;
  }

  /**
   *
   *
   * <pre>
   * Set whether the mic should be muted
   * </pre>
   *
   * <code>bool set_mic_mute = 2;</code>
   *
   * @param value The setMicMute to set.
   */
  private void setSetMicMute(boolean value) {
    msgCase_ = 2;
    msg_ = value;
  }

  /**
   *
   *
   * <pre>
   * Set whether the mic should be muted
   * </pre>
   *
   * <code>bool set_mic_mute = 2;</code>
   */
  private void clearSetMicMute() {
    if (msgCase_ == 2) {
      msgCase_ = 0;
      msg_ = null;
    }
  }

  public static final int SET_DEVICE_VOLUME_FIELD_NUMBER = 3;

  /**
   *
   *
   * <pre>
   * Set the volume of the device
   * </pre>
   *
   * <code>.hassmic.DeviceVolumeChange set_device_volume = 3;</code>
   */
  @java.lang.Override
  public boolean hasSetDeviceVolume() {
    return msgCase_ == 3;
  }

  /**
   *
   *
   * <pre>
   * Set the volume of the device
   * </pre>
   *
   * <code>.hassmic.DeviceVolumeChange set_device_volume = 3;</code>
   */
  @java.lang.Override
  public com.thejeffcooper.hassmic.proto.DeviceVolumeChange getSetDeviceVolume() {
    if (msgCase_ == 3) {
      return (com.thejeffcooper.hassmic.proto.DeviceVolumeChange) msg_;
    }
    return com.thejeffcooper.hassmic.proto.DeviceVolumeChange.getDefaultInstance();
  }

  /**
   *
   *
   * <pre>
   * Set the volume of the device
   * </pre>
   *
   * <code>.hassmic.DeviceVolumeChange set_device_volume = 3;</code>
   */
  private void setSetDeviceVolume(com.thejeffcooper.hassmic.proto.DeviceVolumeChange value) {
    value.getClass();
    msg_ = value;
    msgCase_ = 3;
  }

  /**
   *
   *
   * <pre>
   * Set the volume of the device
   * </pre>
   *
   * <code>.hassmic.DeviceVolumeChange set_device_volume = 3;</code>
   */
  private void mergeSetDeviceVolume(com.thejeffcooper.hassmic.proto.DeviceVolumeChange value) {
    value.getClass();
    if (msgCase_ == 3
        && msg_ != com.thejeffcooper.hassmic.proto.DeviceVolumeChange.getDefaultInstance()) {
      msg_ =
          com.thejeffcooper.hassmic.proto.DeviceVolumeChange.newBuilder(
                  (com.thejeffcooper.hassmic.proto.DeviceVolumeChange) msg_)
              .mergeFrom(value)
              .buildPartial();
    } else {
      msg_ = value;
    }
    msgCase_ = 3;
  }

  /**
   *
   *
   * <pre>
   * Set the volume of the device
   * </pre>
   *
   * <code>.hassmic.DeviceVolumeChange set_device_volume = 3;</code>
   */
  private void clearSetDeviceVolume() {
    if (msgCase_ == 3) {
      msgCase_ = 0;
      msg_ = null;
    }
  }

  public static final int SET_PLAYER_VOLUME_FIELD_NUMBER = 4;

  /**
   *
   *
   * <pre>
   * Set the volume of a player
   * </pre>
   *
   * <code>.hassmic.MediaPlayerVolumeChange set_player_volume = 4;</code>
   */
  @java.lang.Override
  public boolean hasSetPlayerVolume() {
    return msgCase_ == 4;
  }

  /**
   *
   *
   * <pre>
   * Set the volume of a player
   * </pre>
   *
   * <code>.hassmic.MediaPlayerVolumeChange set_player_volume = 4;</code>
   */
  @java.lang.Override
  public com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange getSetPlayerVolume() {
    if (msgCase_ == 4) {
      return (com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange) msg_;
    }
    return com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange.getDefaultInstance();
  }

  /**
   *
   *
   * <pre>
   * Set the volume of a player
   * </pre>
   *
   * <code>.hassmic.MediaPlayerVolumeChange set_player_volume = 4;</code>
   */
  private void setSetPlayerVolume(com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange value) {
    value.getClass();
    msg_ = value;
    msgCase_ = 4;
  }

  /**
   *
   *
   * <pre>
   * Set the volume of a player
   * </pre>
   *
   * <code>.hassmic.MediaPlayerVolumeChange set_player_volume = 4;</code>
   */
  private void mergeSetPlayerVolume(com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange value) {
    value.getClass();
    if (msgCase_ == 4
        && msg_ != com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange.getDefaultInstance()) {
      msg_ =
          com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange.newBuilder(
                  (com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange) msg_)
              .mergeFrom(value)
              .buildPartial();
    } else {
      msg_ = value;
    }
    msgCase_ = 4;
  }

  /**
   *
   *
   * <pre>
   * Set the volume of a player
   * </pre>
   *
   * <code>.hassmic.MediaPlayerVolumeChange set_player_volume = 4;</code>
   */
  private void clearSetPlayerVolume() {
    if (msgCase_ == 4) {
      msgCase_ = 0;
      msg_ = null;
    }
  }

  public static com.thejeffcooper.hassmic.proto.ServerMessage parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.thejeffcooper.hassmic.proto.ServerMessage parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.ServerMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.thejeffcooper.hassmic.proto.ServerMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.ServerMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static com.thejeffcooper.hassmic.proto.ServerMessage parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.ServerMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static com.thejeffcooper.hassmic.proto.ServerMessage parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.ServerMessage parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.thejeffcooper.hassmic.proto.ServerMessage parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.thejeffcooper.hassmic.proto.ServerMessage parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static com.thejeffcooper.hassmic.proto.ServerMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }

  public static Builder newBuilder(com.thejeffcooper.hassmic.proto.ServerMessage prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   *
   *
   * <pre>
   * The wrapper message that gets sent from the server to the client
   * </pre>
   *
   * Protobuf type {@code hassmic.ServerMessage}
   */
  public static final class Builder
      extends com.google.protobuf.GeneratedMessageLite.Builder<
          com.thejeffcooper.hassmic.proto.ServerMessage, Builder>
      implements
      // @@protoc_insertion_point(builder_implements:hassmic.ServerMessage)
      com.thejeffcooper.hassmic.proto.ServerMessageOrBuilder {
    // Construct using com.thejeffcooper.hassmic.proto.ServerMessage.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public MsgCase getMsgCase() {
      return instance.getMsgCase();
    }

    public Builder clearMsg() {
      copyOnWrite();
      instance.clearMsg();
      return this;
    }

    /**
     *
     *
     * <pre>
     * A command to play audio
     * </pre>
     *
     * <code>.hassmic.PlayAudio play_audio = 1;</code>
     */
    @java.lang.Override
    public boolean hasPlayAudio() {
      return instance.hasPlayAudio();
    }

    /**
     *
     *
     * <pre>
     * A command to play audio
     * </pre>
     *
     * <code>.hassmic.PlayAudio play_audio = 1;</code>
     */
    @java.lang.Override
    public com.thejeffcooper.hassmic.proto.PlayAudio getPlayAudio() {
      return instance.getPlayAudio();
    }

    /**
     *
     *
     * <pre>
     * A command to play audio
     * </pre>
     *
     * <code>.hassmic.PlayAudio play_audio = 1;</code>
     */
    public Builder setPlayAudio(com.thejeffcooper.hassmic.proto.PlayAudio value) {
      copyOnWrite();
      instance.setPlayAudio(value);
      return this;
    }

    /**
     *
     *
     * <pre>
     * A command to play audio
     * </pre>
     *
     * <code>.hassmic.PlayAudio play_audio = 1;</code>
     */
    public Builder setPlayAudio(com.thejeffcooper.hassmic.proto.PlayAudio.Builder builderForValue) {
      copyOnWrite();
      instance.setPlayAudio(builderForValue.build());
      return this;
    }

    /**
     *
     *
     * <pre>
     * A command to play audio
     * </pre>
     *
     * <code>.hassmic.PlayAudio play_audio = 1;</code>
     */
    public Builder mergePlayAudio(com.thejeffcooper.hassmic.proto.PlayAudio value) {
      copyOnWrite();
      instance.mergePlayAudio(value);
      return this;
    }

    /**
     *
     *
     * <pre>
     * A command to play audio
     * </pre>
     *
     * <code>.hassmic.PlayAudio play_audio = 1;</code>
     */
    public Builder clearPlayAudio() {
      copyOnWrite();
      instance.clearPlayAudio();
      return this;
    }

    /**
     *
     *
     * <pre>
     * Set whether the mic should be muted
     * </pre>
     *
     * <code>bool set_mic_mute = 2;</code>
     *
     * @return Whether the setMicMute field is set.
     */
    @java.lang.Override
    public boolean hasSetMicMute() {
      return instance.hasSetMicMute();
    }

    /**
     *
     *
     * <pre>
     * Set whether the mic should be muted
     * </pre>
     *
     * <code>bool set_mic_mute = 2;</code>
     *
     * @return The setMicMute.
     */
    @java.lang.Override
    public boolean getSetMicMute() {
      return instance.getSetMicMute();
    }

    /**
     *
     *
     * <pre>
     * Set whether the mic should be muted
     * </pre>
     *
     * <code>bool set_mic_mute = 2;</code>
     *
     * @param value The setMicMute to set.
     * @return This builder for chaining.
     */
    public Builder setSetMicMute(boolean value) {
      copyOnWrite();
      instance.setSetMicMute(value);
      return this;
    }

    /**
     *
     *
     * <pre>
     * Set whether the mic should be muted
     * </pre>
     *
     * <code>bool set_mic_mute = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearSetMicMute() {
      copyOnWrite();
      instance.clearSetMicMute();
      return this;
    }

    /**
     *
     *
     * <pre>
     * Set the volume of the device
     * </pre>
     *
     * <code>.hassmic.DeviceVolumeChange set_device_volume = 3;</code>
     */
    @java.lang.Override
    public boolean hasSetDeviceVolume() {
      return instance.hasSetDeviceVolume();
    }

    /**
     *
     *
     * <pre>
     * Set the volume of the device
     * </pre>
     *
     * <code>.hassmic.DeviceVolumeChange set_device_volume = 3;</code>
     */
    @java.lang.Override
    public com.thejeffcooper.hassmic.proto.DeviceVolumeChange getSetDeviceVolume() {
      return instance.getSetDeviceVolume();
    }

    /**
     *
     *
     * <pre>
     * Set the volume of the device
     * </pre>
     *
     * <code>.hassmic.DeviceVolumeChange set_device_volume = 3;</code>
     */
    public Builder setSetDeviceVolume(com.thejeffcooper.hassmic.proto.DeviceVolumeChange value) {
      copyOnWrite();
      instance.setSetDeviceVolume(value);
      return this;
    }

    /**
     *
     *
     * <pre>
     * Set the volume of the device
     * </pre>
     *
     * <code>.hassmic.DeviceVolumeChange set_device_volume = 3;</code>
     */
    public Builder setSetDeviceVolume(
        com.thejeffcooper.hassmic.proto.DeviceVolumeChange.Builder builderForValue) {
      copyOnWrite();
      instance.setSetDeviceVolume(builderForValue.build());
      return this;
    }

    /**
     *
     *
     * <pre>
     * Set the volume of the device
     * </pre>
     *
     * <code>.hassmic.DeviceVolumeChange set_device_volume = 3;</code>
     */
    public Builder mergeSetDeviceVolume(com.thejeffcooper.hassmic.proto.DeviceVolumeChange value) {
      copyOnWrite();
      instance.mergeSetDeviceVolume(value);
      return this;
    }

    /**
     *
     *
     * <pre>
     * Set the volume of the device
     * </pre>
     *
     * <code>.hassmic.DeviceVolumeChange set_device_volume = 3;</code>
     */
    public Builder clearSetDeviceVolume() {
      copyOnWrite();
      instance.clearSetDeviceVolume();
      return this;
    }

    /**
     *
     *
     * <pre>
     * Set the volume of a player
     * </pre>
     *
     * <code>.hassmic.MediaPlayerVolumeChange set_player_volume = 4;</code>
     */
    @java.lang.Override
    public boolean hasSetPlayerVolume() {
      return instance.hasSetPlayerVolume();
    }

    /**
     *
     *
     * <pre>
     * Set the volume of a player
     * </pre>
     *
     * <code>.hassmic.MediaPlayerVolumeChange set_player_volume = 4;</code>
     */
    @java.lang.Override
    public com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange getSetPlayerVolume() {
      return instance.getSetPlayerVolume();
    }

    /**
     *
     *
     * <pre>
     * Set the volume of a player
     * </pre>
     *
     * <code>.hassmic.MediaPlayerVolumeChange set_player_volume = 4;</code>
     */
    public Builder setSetPlayerVolume(
        com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange value) {
      copyOnWrite();
      instance.setSetPlayerVolume(value);
      return this;
    }

    /**
     *
     *
     * <pre>
     * Set the volume of a player
     * </pre>
     *
     * <code>.hassmic.MediaPlayerVolumeChange set_player_volume = 4;</code>
     */
    public Builder setSetPlayerVolume(
        com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange.Builder builderForValue) {
      copyOnWrite();
      instance.setSetPlayerVolume(builderForValue.build());
      return this;
    }

    /**
     *
     *
     * <pre>
     * Set the volume of a player
     * </pre>
     *
     * <code>.hassmic.MediaPlayerVolumeChange set_player_volume = 4;</code>
     */
    public Builder mergeSetPlayerVolume(
        com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange value) {
      copyOnWrite();
      instance.mergeSetPlayerVolume(value);
      return this;
    }

    /**
     *
     *
     * <pre>
     * Set the volume of a player
     * </pre>
     *
     * <code>.hassmic.MediaPlayerVolumeChange set_player_volume = 4;</code>
     */
    public Builder clearSetPlayerVolume() {
      copyOnWrite();
      instance.clearSetPlayerVolume();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:hassmic.ServerMessage)
  }

  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0,
      java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE:
        {
          return new com.thejeffcooper.hassmic.proto.ServerMessage();
        }
      case NEW_BUILDER:
        {
          return new Builder();
        }
      case BUILD_MESSAGE_INFO:
        {
          java.lang.Object[] objects =
              new java.lang.Object[] {
                "msg_",
                "msgCase_",
                com.thejeffcooper.hassmic.proto.PlayAudio.class,
                com.thejeffcooper.hassmic.proto.DeviceVolumeChange.class,
                com.thejeffcooper.hassmic.proto.MediaPlayerVolumeChange.class,
              };
          java.lang.String info =
              "\u0000\u0004\u0001\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001<\u0000\u0002:"
                  + "\u0000\u0003<\u0000\u0004<\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
      case GET_DEFAULT_INSTANCE:
        {
          return DEFAULT_INSTANCE;
        }
      case GET_PARSER:
        {
          com.google.protobuf.Parser<com.thejeffcooper.hassmic.proto.ServerMessage> parser = PARSER;
          if (parser == null) {
            synchronized (com.thejeffcooper.hassmic.proto.ServerMessage.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<com.thejeffcooper.hassmic.proto.ServerMessage>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
      case GET_MEMOIZED_IS_INITIALIZED:
        {
          return (byte) 1;
        }
      case SET_MEMOIZED_IS_INITIALIZED:
        {
          return null;
        }
    }
    throw new UnsupportedOperationException();
  }

  // @@protoc_insertion_point(class_scope:hassmic.ServerMessage)
  private static final com.thejeffcooper.hassmic.proto.ServerMessage DEFAULT_INSTANCE;

  static {
    ServerMessage defaultInstance = new ServerMessage();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ServerMessage.class, defaultInstance);
  }

  public static com.thejeffcooper.hassmic.proto.ServerMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ServerMessage> PARSER;

  public static com.google.protobuf.Parser<ServerMessage> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
