// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hassmic.proto

package com.thejeffcooper.hassmic.proto;

public interface ServerMessageOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:hassmic.ServerMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.hassmic.PlayAudio play_audio = 1;</code>
   *
   * @return Whether the playAudio field is set.
   */
  boolean hasPlayAudio();

  /**
   * <code>.hassmic.PlayAudio play_audio = 1;</code>
   *
   * @return The playAudio.
   */
  com.thejeffcooper.hassmic.proto.PlayAudio getPlayAudio();

  public com.thejeffcooper.hassmic.proto.ServerMessage.MsgCase getMsgCase();
}
