# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hassmic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rhassmic.proto\x12\x07hassmic"+\n\nClientInfo\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t"\x06\n\x04Ping"\x19\n\tAudioData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c":\n\x13\x43lientEventOccurred\x12#\n\x05\x65vent\x18\x01 \x01(\x0e\x32\x14.hassmic.ClientEvent"\xbb\x01\n\rClientMessage\x12\x1d\n\x04ping\x18\x01 \x01(\x0b\x32\r.hassmic.PingH\x00\x12*\n\x0b\x63lient_info\x18\x02 \x01(\x0b\x32\x13.hassmic.ClientInfoH\x00\x12(\n\naudio_data\x18\x03 \x01(\x0b\x32\x12.hassmic.AudioDataH\x00\x12.\n\x0e\x65vent_occurred\x18\x04 \x01(\x0e\x32\x14.hassmic.ClientEventH\x00\x42\x05\n\x03msg* \n\x0b\x43lientEvent\x12\x11\n\rUNKNOWN_EVENT\x10\x00\x42#\n\x1f\x63om.thejeffcooper.hassmic.protoP\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "hassmic_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\037com.thejeffcooper.hassmic.protoP\001"
    _globals["_CLIENTEVENT"]._serialized_start = 356
    _globals["_CLIENTEVENT"]._serialized_end = 388
    _globals["_CLIENTINFO"]._serialized_start = 26
    _globals["_CLIENTINFO"]._serialized_end = 69
    _globals["_PING"]._serialized_start = 71
    _globals["_PING"]._serialized_end = 77
    _globals["_AUDIODATA"]._serialized_start = 79
    _globals["_AUDIODATA"]._serialized_end = 104
    _globals["_CLIENTEVENTOCCURRED"]._serialized_start = 106
    _globals["_CLIENTEVENTOCCURRED"]._serialized_end = 164
    _globals["_CLIENTMESSAGE"]._serialized_start = 167
    _globals["_CLIENTMESSAGE"]._serialized_end = 354
# @@protoc_insertion_point(module_scope)
