# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/hassmic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13proto/hassmic.proto\x12\x07hassmic"+\n\nClientInfo\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t"\x06\n\x04Ping"\x19\n\tAudioData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c"a\n\rClientMessage\x12\x1d\n\x04ping\x18\x01 \x01(\x0b\x32\r.hassmic.PingH\x00\x12*\n\x0b\x63lient_info\x18\x02 \x01(\x0b\x32\x13.hassmic.ClientInfoH\x00\x42\x05\n\x03msgB#\n\x1f\x63om.thejeffcooper.hassmic.protoP\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "proto.hassmic_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\037com.thejeffcooper.hassmic.protoP\001"
    _globals["_CLIENTINFO"]._serialized_start = 32
    _globals["_CLIENTINFO"]._serialized_end = 75
    _globals["_PING"]._serialized_start = 77
    _globals["_PING"]._serialized_end = 83
    _globals["_AUDIODATA"]._serialized_start = 85
    _globals["_AUDIODATA"]._serialized_end = 110
    _globals["_CLIENTMESSAGE"]._serialized_start = 112
    _globals["_CLIENTMESSAGE"]._serialized_end = 209
# @@protoc_insertion_point(module_scope)
